"""update models

Revision ID: 2a601e2be70a
Revises: 8ce95e8d8003
Create Date: 2025-08-12 10:33:48.853203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a601e2be70a'
down_revision = '8ce95e8d8003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
