"""Add nested replies and role display

Revision ID: 62ee8d11f9a8
Revises: fe1f723bfe97
Create Date: 2025-08-11 02:35:37.462860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ee8d11f9a8'
down_revision = 'fe1f723bfe97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_reply_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_replies_parent_reply_id', 'replies', ['parent_reply_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_replies_parent_reply_id', type_='foreignkey')
        batch_op.drop_column('parent_reply_id')

    # ### end Alembic commands ###
