"""Add file_path to Assignment model

Revision ID: 63c0faa1ad9c
Revises: e79b2707d739
Create Date: 2025-08-08 17:27:53.614108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c0faa1ad9c'
down_revision = 'e79b2707d739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
