"""update

Revision ID: cd9c8674b1c7
Revises: 21ad61b9603d
Create Date: 2025-08-08 12:27:31.087244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9c8674b1c7'
down_revision = '21ad61b9603d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_dates', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_quiz_submission_submission_dates'), ['submission_dates'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_submission_submission_dates'))
        batch_op.drop_column('submission_dates')

    # ### end Alembic commands ###
