"""upgrade

Revision ID: e79b2707d739
Revises: cd9c8674b1c7
Create Date: 2025-08-08 12:47:10.935117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79b2707d739'
down_revision = 'cd9c8674b1c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_graded', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_submission', schema=None) as batch_op:
        batch_op.drop_column('is_graded')

    # ### end Alembic commands ###
