"""add columns max_submission and submissions to Assignment model

Revision ID: eb5380dd2ba4
Revises: 63c0faa1ad9c
Create Date: 2025-08-08 18:37:45.116062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb5380dd2ba4'
down_revision = '63c0faa1ad9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_submissions', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_column('max_submissions')

    # ### end Alembic commands ###
