"""add file_path to course model

Revision ID: fe1f723bfe97
Revises: eb5380dd2ba4
Create Date: 2025-08-09 08:04:28.515775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1f723bfe97'
down_revision = 'eb5380dd2ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=300), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
